<a href="https://colab.research.google.com/github/YKXu-c/MachineLearning_pytorch_RL_DLExamples/blob/main/00_basical_pytorch_using.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Basic opearation of pytorch
Resource: My note https://rust.oakk.space/article/29224ed4-ef88-80f1-9413-f86ee4e3344a and mrdbourke's great cource https://github.com/mrdbourke/pytorch-deep-learning

In [1]:

print("Just a test!")


Just a test!


In [2]:

!nvidia-smi


Tue Nov 11 10:03:39 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   36C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
import torch
print(torch.__version__)

2.8.0+cu126


In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# These are used for data reading, tensor/matrix, data plotting

## Tensors
### Creating tensors

In [5]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
scalar.item()

7

In [8]:
# Vector
vector = torch.tensor([6,7])
vector



tensor([6, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
#Matrix
Matrix = torch.tensor([[11,12],
            [21,22]])
Matrix

tensor([[11, 12],
        [21, 22]])

In [12]:
Matrix.ndim

2

In [13]:
Matrix[0]


tensor([11, 12])

In [14]:
Matrix.shape

torch.Size([2, 2])

In [15]:
#TENSOR of order 3
TENSOR1 = torch.tensor([[[11,12,13],
            [21,22,23],
            [31,32,33]]])
TENSOR1

tensor([[[11, 12, 13],
         [21, 22, 23],
         [31, 32, 33]]])

In [16]:
TENSOR1.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR2 = torch.tensor([[[11,12,13],
            [21,22,23]]])
TENSOR2.shape

torch.Size([1, 2, 3])

In [18]:
len(TENSOR2) # method len() just gives the highest order of a tensor

1

In [19]:
# TENSOR3 = torch.tensor([[[11,13],
#             [21,22,23]]])
# TENSOR3.shape

The dimension of "sub" tensor should be the same. You can run this block and see the Error given by compiler.

### Random tensors
Why random tensors?
We can indentify any tensor by give exact elements.
In a neural net works learn, start from a random tensor is a btter choice.
Then we can adjust elements in this tensor to represent data properly.
`Start with random numbers -> look at data -> update randm numbers -> look at data -> update -> ......
Check Torch.RAND

In [20]:
# Create a random tensor of size (3,4) which is a matrix (have 3 vectors and each vector has 4 scalar)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7978, 0.7913, 0.7426, 0.9931],
        [0.3628, 0.9636, 0.7701, 0.3368],
        [0.6038, 0.7129, 0.1124, 0.3467]])

In [21]:
# Create a random tensor with similar shape to an image tensor
# a image tensor should have 3 dimensions: hight, width, color
random_image_size_tensor = torch.rand(size=(3,224,224))# color, hight, width
random_image_size_tensor

tensor([[[0.8597, 0.2645, 0.3487,  ..., 0.3374, 0.6539, 0.8867],
         [0.6133, 0.0212, 0.3966,  ..., 0.4681, 0.3540, 0.4656],
         [0.2245, 0.2702, 0.6931,  ..., 0.7173, 0.3743, 0.6336],
         ...,
         [0.5938, 0.3895, 0.2725,  ..., 0.5332, 0.4097, 0.1923],
         [0.4496, 0.6244, 0.4139,  ..., 0.8198, 0.9507, 0.6364],
         [0.0066, 0.8470, 0.1319,  ..., 0.4835, 0.2379, 0.9282]],

        [[0.4497, 0.6776, 0.6184,  ..., 0.3706, 0.0568, 0.9746],
         [0.9206, 0.8804, 0.5080,  ..., 0.4089, 0.6408, 0.9621],
         [0.4582, 0.0408, 0.9069,  ..., 0.4792, 0.9721, 0.1532],
         ...,
         [0.5282, 0.7968, 0.0939,  ..., 0.2144, 0.6361, 0.2505],
         [0.8961, 0.2259, 0.5386,  ..., 0.9581, 0.3082, 0.6175],
         [0.3951, 0.9844, 0.4319,  ..., 0.0979, 0.1029, 0.4002]],

        [[0.1410, 0.7597, 0.1652,  ..., 0.1852, 0.4106, 0.4763],
         [0.7882, 0.3436, 0.9197,  ..., 0.0121, 0.6736, 0.6276],
         [0.5767, 0.5502, 0.0373,  ..., 0.5673, 0.3600, 0.

In this way, we can represent any images into a tensor in pytorch saved in our memory of computer.

### Create a tensor with only Zeros or ones

In [22]:
# create a tensor with all zeros
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
# create a tensor with all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

A tensor has a property called (dataType)


In [24]:
ones.dtype

torch.float32

### Create a range of tensors and tensors-like

In [25]:
torch.range(0,10)

/tmp/ipython-input-497691777.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [26]:
one_to_ten = torch.arange(1,11)#torch.arange(start = 1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
one_to_101 = torch.arange(start = 1, end=101, step=6)
one_to_101

tensor([ 1,  7, 13, 19, 25, 31, 37, 43, 49, 55, 61, 67, 73, 79, 85, 91, 97])

If we want to create a tensor with just the same shape of a tensor we already generated, we can do as below:

In [28]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
many_zeros = torch.zeros_like(input=random_image_size_tensor)
many_zeros

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])

### Tensor datatypes (attributes)
**Note:** There are 3 normal errors when we run into with Pytorch
1. wrong datatype, `tensor.dtype`
2. wrong shape, `tensor.shape` or `tensor.size()`
3. not on right device, `tensor.device`

In [30]:
# Float 32 tensor(defalut if we type a decimal number)
float_32_tensor = torch.tensor([3.0,6,9],dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [31]:
float_32_tensor.dtype

torch.float32

In [32]:
int_64_tensor = torch.tensor([3,6,9],dtype=None)
int_64_tensor

tensor([3, 6, 9])

In [33]:
int_64_tensor.dtype

torch.int64

In [34]:
# change to certain datatype
float_16_tensor = torch.tensor([3,6,9],dtype=torch.float16)
print(float_16_tensor,"'s datatype is ",float_16_tensor.dtype)

tensor([3., 6., 9.], dtype=torch.float16) 's datatype is  torch.float16


In [35]:
# basic parameters
a_torch_tensor = torch.tensor([3.0,6.0,9.0],
                dtype=None,   # different precision of numbers in a torch.tensor, there are also complex number, torch.complex32
                device=None,   # cpu,cuda,etc.
                requires_grad=False) # whether or not to track the gradient of tensor

In [36]:
another_torch_tensor = torch.tensor([3.0,6.0,9.0],
                dtype=torch.complex64,   # different precision of numbers in a torch.tensor, there are also complex number, torch.complex32
                device='cuda',   # cpu,cuda,etc.
                requires_grad=True) # whether or not to track the gradient of tensor
print(f"{another_torch_tensor}'s datatype is {another_torch_tensor.dtype}")

tensor([3.+0.j, 6.+0.j, 9.+0.j], device='cuda:0', requires_grad=True)'s datatype is torch.complex64


### Manipulating Tensors （tensor operations）
* Addition
* Subtraction
* Multiplication
* Division
* Matrix multiplication


In [37]:
# Create a tensor and add 10 to it
temp_tensor = torch.rand(2,3,4)
temp_tensor_prime = temp_tensor+10
print(f"initial random tensor is {temp_tensor}, after operation being{temp_tensor_prime}")

initial random tensor is tensor([[[0.3377, 0.7897, 0.0520, 0.2874],
         [0.5543, 0.4585, 0.6063, 0.5359],
         [0.7567, 0.1448, 0.0238, 0.4190]],

        [[0.1906, 0.7290, 0.5357, 0.7521],
         [0.6786, 0.9936, 0.3416, 0.1465],
         [0.6790, 0.3018, 0.3462, 0.5932]]]), after operation beingtensor([[[10.3377, 10.7897, 10.0520, 10.2874],
         [10.5543, 10.4585, 10.6063, 10.5359],
         [10.7567, 10.1448, 10.0238, 10.4190]],

        [[10.1906, 10.7290, 10.5357, 10.7521],
         [10.6786, 10.9936, 10.3416, 10.1465],
         [10.6790, 10.3018, 10.3462, 10.5932]]])


In [38]:
# Substract is similiar
temp_tensor = torch.rand(2,3,4)
temp_tensor_pp = torch.rand_like(input=temp_tensor)
temp_tensor_prime = temp_tensor-temp_tensor_pp
print(f"initial random tensors is {temp_tensor}\n and {temp_tensor_pp},\n after operation being{temp_tensor_prime}")

initial random tensors is tensor([[[0.5164, 0.4602, 0.8494, 0.7241],
         [0.0052, 0.5680, 0.4179, 0.0091],
         [0.4156, 0.1334, 0.5351, 0.4658]],

        [[0.4968, 0.3740, 0.9744, 0.5637],
         [0.2678, 0.1952, 0.6952, 0.7229],
         [0.9960, 0.7082, 0.9481, 0.5541]]])
 and tensor([[[0.3768, 0.7376, 0.0397, 0.0516],
         [0.9767, 0.1200, 0.8301, 0.1210],
         [0.9086, 0.3394, 0.2801, 0.4052]],

        [[0.5953, 0.5304, 0.5683, 0.8472],
         [0.0093, 0.8637, 0.2797, 0.3081],
         [0.8578, 0.3331, 0.8859, 0.2164]]]),
 after operation beingtensor([[[ 0.1396, -0.2774,  0.8097,  0.6725],
         [-0.9715,  0.4480, -0.4122, -0.1119],
         [-0.4930, -0.2060,  0.2550,  0.0606]],

        [[-0.0985, -0.1564,  0.4061, -0.2834],
         [ 0.2586, -0.6685,  0.4155,  0.4148],
         [ 0.1382,  0.3751,  0.0622,  0.3377]]])


Then we takle a look at multiplication and matrix multiplication of tensors

In [39]:
temp_tensor = float_16_tensor * float_32_tensor
print(temp_tensor,temp_tensor.dtype)

tensor([ 9., 36., 81.]) torch.float32


In [40]:
temp_tensor = int_64_tensor * float_32_tensor
print(temp_tensor,temp_tensor.dtype)

tensor([ 9., 36., 81.]) torch.float32


This is just multiplicating elements with same index and put them into a new tensor.

We can use matrix multiplication (dot product,just like in `Matlab`) to achieve tensor contraction.


In [41]:
temp_tensor = torch.matmul(float_16_tensor, float_16_tensor)
print(f"initial tensor is {float_16_tensor}, result is {temp_tensor}")

initial tensor is tensor([3., 6., 9.], dtype=torch.float16), result is 126.0


In [42]:
%%time
float_16_tensor_prime = torch.tensor([[1,2,3],[1,2,3]])
temp_tensor = torch.matmul(float_16_tensor_prime, torch.transpose(float_16_tensor_prime,0,1))
# Here we use the method transpose to transpose tensor(2*3) to (3*2)
# Attention! the arguments 0,1 is to label which two index of tensor we want to trans
print(f"initial tensor is {float_16_tensor_prime}with size {float_16_tensor_prime.size()}, result is {temp_tensor}")
# From the result and recall the rule of matrix multiplication, we can see matrix in torch.tensor is saved by row

initial tensor is tensor([[1, 2, 3],
        [1, 2, 3]])with size torch.Size([2, 3]), result is tensor([[14, 14],
        [14, 14]])
CPU times: user 1.24 ms, sys: 80 µs, total: 1.32 ms
Wall time: 2.97 ms


In [43]:
# If you are familiar with contraction of tensor and Einstain sum rule, we can do this:
%%time
random_tensor = torch.rand(2,3,4)
random_tensor_trans13 = torch.transpose(random_tensor,0,2)
temp_tensor = torch.einsum('ijk,kji->',[random_tensor,random_tensor_trans13])
print(f"initial tensor is {random_tensor}\n result is {temp_tensor}")

initial tensor is tensor([[[7.6389e-01, 8.9561e-01, 7.5498e-01, 1.6617e-02],
         [5.2278e-01, 4.0263e-01, 8.1614e-01, 5.0102e-02],
         [4.8584e-02, 6.6609e-01, 9.4409e-01, 1.7818e-01]],

        [[4.0157e-02, 3.3531e-02, 9.4390e-01, 6.4287e-01],
         [3.3796e-01, 6.8390e-04, 5.2711e-01, 6.9153e-01],
         [2.1597e-01, 1.4982e-01, 2.2402e-01, 3.5362e-01]]])
 result is 6.8505706787109375
CPU times: user 13.4 ms, sys: 276 µs, total: 13.6 ms
Wall time: 16.1 ms


In [44]:
# A test of superlarge tensor contraction
# If the video memory is enough, this is super effective in cuda
%%time
random_tensor = torch.rand(size=(1000,300,4000),device='cuda')
random_tensor_trans13 = torch.transpose(random_tensor,0,2)
temp_tensor = torch.einsum('ijk,kji->',[random_tensor,random_tensor_trans13])
print(f"initial tensor is {random_tensor}\n result is {temp_tensor}")

initial tensor is tensor([[[0.6835, 0.7348, 0.0540,  ..., 0.5924, 0.4759, 0.6839],
         [0.5369, 0.0885, 0.3892,  ..., 0.8420, 0.1725, 0.5006],
         [0.2504, 0.9762, 0.3401,  ..., 0.6715, 0.5060, 0.4961],
         ...,
         [0.2392, 0.3792, 0.5288,  ..., 0.4181, 0.6887, 0.7561],
         [0.2047, 0.5510, 0.5095,  ..., 0.6117, 0.4950, 0.4054],
         [0.5910, 0.9893, 0.0422,  ..., 0.9887, 0.0855, 0.7117]],

        [[0.1445, 0.0994, 0.4401,  ..., 0.3303, 0.0614, 0.1435],
         [0.3752, 0.5244, 0.6986,  ..., 0.0466, 0.7393, 0.2388],
         [0.0810, 0.0782, 0.6551,  ..., 0.4496, 0.9929, 0.0333],
         ...,
         [0.2959, 0.8166, 0.7870,  ..., 0.0028, 0.7374, 0.1450],
         [0.3981, 0.7744, 0.5645,  ..., 0.9669, 0.2490, 0.4112],
         [0.8555, 0.4099, 0.4089,  ..., 0.5712, 0.0537, 0.9524]],

        [[0.0365, 0.7407, 0.4479,  ..., 0.9598, 0.0213, 0.4389],
         [0.7300, 0.5984, 0.6075,  ..., 0.0285, 0.7524, 0.5339],
         [0.1640, 0.0254, 0.4026,  ..., 

### Finding the min,max,mean,sum,etc of a tensor(tensor aggregation，统计)

In [45]:
temp_tensor = torch.rand(2,3,4)
max = torch.mean(temp_tensor)
print(f"The tensor is {temp_tensor},\n \
the min is{torch.min(temp_tensor)}\n \
the max is {torch.max(temp_tensor)}\n \
the mean is {torch.mean(temp_tensor)}")
print(f"the dtype of it is: {max.dtype}")
# Attention! torch.mean requires the dtype of element of tensor being float or complex
# Or this way to use methods:
print(temp_tensor.mean())
print(f"the dtype of it is: {temp_tensor.mean().dtype}")
print(temp_tensor.type(torch.complex128).mean())
# They have the same dtype but different display, that is caused by print/printf
print(f"{temp_tensor.mean()}")
# printf call the __repr__ method of tensor, but print call __str__

The tensor is tensor([[[0.1927, 0.8341, 0.1238, 0.4192],
         [0.6728, 0.0997, 0.1197, 0.6683],
         [0.9297, 0.3542, 0.1354, 0.5056]],

        [[0.5894, 0.4071, 0.1875, 0.3403],
         [0.1055, 0.4764, 0.1756, 0.6084],
         [0.1190, 0.1764, 0.2971, 0.3650]]]),
 the min is0.09972035884857178
 the max is 0.9296658635139465
 the mean is 0.37095019221305847
the dtype of it is: torch.float32
tensor(0.3710)
the dtype of it is: torch.float32
tensor(0.3710+0.j, dtype=torch.complex128)
0.37095019221305847


### Finding positional min and max
* That means we find the argument(index) of the min in torch.**tensor**

In [46]:
# argmin is used to find the argument of min in a list or an array.
#
print(f"tensor is {temp_tensor}\n \
position of min is {temp_tensor.argmin()}\n \
position of min is {torch.unravel_index(temp_tensor.argmin(),temp_tensor.shape)}")
# unravel_index helps us translate 1-dim index to coordinate of .shape

tensor is tensor([[[0.1927, 0.8341, 0.1238, 0.4192],
         [0.6728, 0.0997, 0.1197, 0.6683],
         [0.9297, 0.3542, 0.1354, 0.5056]],

        [[0.5894, 0.4071, 0.1875, 0.3403],
         [0.1055, 0.4764, 0.1756, 0.6084],
         [0.1190, 0.1764, 0.2971, 0.3650]]])
 position of min is 5
 position of min is (tensor(0), tensor(1), tensor(1))


## Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor(like the same tensor but different perspective, always same memory!)
* Stacking - combines seceral tensors in certain way: h-stack, v-stack, side-by-side, etc.
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add `1` dimension into a target tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way(We can say that *斜体文本*`Permute` changes the dimension of layer in a tensor)


In [47]:
# use x for easy typing code
x = torch.rand(2,3,4)
print(f"{x}")

tensor([[[0.1590, 0.5725, 0.6086, 0.6734],
         [0.6083, 0.5410, 0.4303, 0.5097],
         [0.8249, 0.1094, 0.3246, 0.0106]],

        [[0.3394, 0.8433, 0.7913, 0.3265],
         [0.7241, 0.1773, 0.5699, 0.6387],
         [0.4409, 0.9639, 0.2996, 0.5195]]])


In [48]:
# Using of reshape:must has the same number of elements
x_reshaped = x.reshape(2,2,3,2)
print(f"original:{x} \n \
after reshaping: {x_reshaped},\n \
shape is {x_reshaped.shape}")

original:tensor([[[0.1590, 0.5725, 0.6086, 0.6734],
         [0.6083, 0.5410, 0.4303, 0.5097],
         [0.8249, 0.1094, 0.3246, 0.0106]],

        [[0.3394, 0.8433, 0.7913, 0.3265],
         [0.7241, 0.1773, 0.5699, 0.6387],
         [0.4409, 0.9639, 0.2996, 0.5195]]]) 
 after reshaping: tensor([[[[0.1590, 0.5725],
          [0.6086, 0.6734],
          [0.6083, 0.5410]],

         [[0.4303, 0.5097],
          [0.8249, 0.1094],
          [0.3246, 0.0106]]],


        [[[0.3394, 0.8433],
          [0.7913, 0.3265],
          [0.7241, 0.1773]],

         [[0.5699, 0.6387],
          [0.4409, 0.9639],
          [0.2996, 0.5195]]]]),
 shape is torch.Size([2, 2, 3, 2])


We see that reshape does not change the element order of tensor, just change them into a new tensor with the same total size.

#### Change the view of tensor

In [49]:
# Change the view of tensor
z = x.view(2,2,3,2)
z, z.shape

(tensor([[[[0.1590, 0.5725],
           [0.6086, 0.6734],
           [0.6083, 0.5410]],
 
          [[0.4303, 0.5097],
           [0.8249, 0.1094],
           [0.3246, 0.0106]]],
 
 
         [[[0.3394, 0.8433],
           [0.7913, 0.3265],
           [0.7241, 0.1773]],
 
          [[0.5699, 0.6387],
           [0.4409, 0.9639],
           [0.2996, 0.5195]]]]),
 torch.Size([2, 2, 3, 2]))

It seems like there is no different with reshape!

If we check the memory, we will find they share the same memory storage.

Well, the difference between reshape and view is that `view` requeires a continuing storage space.

In [50]:
id(x),id(z),id(x_reshaped)

(137132925783328, 137132922631216, 137132915347360)

In [51]:
x.storage().data_ptr, z.storage().data_ptr, x_reshaped.storage().data_ptr

/tmp/ipython-input-3045457666.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  x.storage().data_ptr, z.storage().data_ptr, x_reshaped.storage().data_ptr


(<bound method TypedStorage.data_ptr of  0.15903162956237793
  0.5725387334823608
  0.6085910797119141
  0.6734214425086975
  0.6083411574363708
  0.541006863117218
  0.43030649423599243
  0.5096519589424133
  0.8248898386955261
  0.10935276746749878
  0.32464927434921265
  0.010597288608551025
  0.3393794298171997
  0.8433186411857605
  0.7913108468055725
  0.32653677463531494
  0.724108099937439
  0.17732131481170654
  0.569884717464447
  0.6386775374412537
  0.44089972972869873
  0.9638655781745911
  0.2996327877044678
  0.5194552540779114
 [torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 24]>,
 <bound method TypedStorage.data_ptr of  0.15903162956237793
  0.5725387334823608
  0.6085910797119141
  0.6734214425086975
  0.6083411574363708
  0.541006863117218
  0.43030649423599243
  0.5096519589424133
  0.8248898386955261
  0.10935276746749878
  0.32464927434921265
  0.010597288608551025
  0.3393794298171997
  0.8433186411857605
  0.7913108468055725
  0.326536774635


#### Stack tensor from top to each orther.

 Let us just take a simply example


In [59]:
# Stack tensor from top to each orther. Let us just take a simply example
x = torch.rand(2,3)
x_stacked_dim0 = torch.stack([x,x,x],dim=0)
x_stacked_dim1 = torch.stack([x,x,x],dim=1)
x_stacked_dim2 = torch.stack([x,x,x],dim=2)
x_stacked_dim_minus_2 = torch.stack([x,x,x],dim=-2)
x,x_stacked_dim0,x_stacked_dim1,x_stacked_dim2,x_stacked_dim_minus_2

(tensor([[0.9452, 0.7096, 0.0522],
         [0.4481, 0.5075, 0.3056]]),
 tensor([[[0.9452, 0.7096, 0.0522],
          [0.4481, 0.5075, 0.3056]],
 
         [[0.9452, 0.7096, 0.0522],
          [0.4481, 0.5075, 0.3056]],
 
         [[0.9452, 0.7096, 0.0522],
          [0.4481, 0.5075, 0.3056]]]),
 tensor([[[0.9452, 0.7096, 0.0522],
          [0.9452, 0.7096, 0.0522],
          [0.9452, 0.7096, 0.0522]],
 
         [[0.4481, 0.5075, 0.3056],
          [0.4481, 0.5075, 0.3056],
          [0.4481, 0.5075, 0.3056]]]),
 tensor([[[0.9452, 0.9452, 0.9452],
          [0.7096, 0.7096, 0.7096],
          [0.0522, 0.0522, 0.0522]],
 
         [[0.4481, 0.4481, 0.4481],
          [0.5075, 0.5075, 0.5075],
          [0.3056, 0.3056, 0.3056]]]))

`dim`: The dimension along which to stack the tensors.

In above examples:
x has shape `2*3`

`dim=0`: `2*3` -> `3*2*3`, the new dimension inserts in front of any layers

`dim=1`: `2*3` -> `2*3*3`, the new dimension inserts between index [0] and index [1]

`dim=2`: `2*3` -> `2*3*3`, the new dimension inserts between index [1] and index [2]

`dim=-2`: the lowerst layer has 3 elements, so `-2` is the same as `1`, just like the index of list in `python`.

#### torch.squeeze()
- removing 1-dimension from a target tensor


In [70]:
# use zeros to look at squeeze method
x = torch.zeros(2,2,1,2,1,2)
y1 = torch.squeeze(x)
y2 = torch.squeeze(x,0)
y3 = torch.squeeze(x,1)
y4 = torch.squeeze(x,dim=2)
y5 = torch.squeeze(x,dim=(2,4))
print(f"x:{x}\n {x.size()}\n \
y1:{y1}\n {y1.size()}\n \
y2:{y2}\n {y2.size()}\n \
y3:{y3}\n {y3.size()}\n \
y4:{y4}\n {y4.size()}\n \
y5:{y5}\n {y5.size()}\n")

x:tensor([[[[[[0., 0.]],

           [[0., 0.]]]],



         [[[[0., 0.]],

           [[0., 0.]]]]],




        [[[[[0., 0.]],

           [[0., 0.]]]],



         [[[[0., 0.]],

           [[0., 0.]]]]]])
 torch.Size([2, 2, 1, 2, 1, 2])
 y1:tensor([[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]])
 torch.Size([2, 2, 2, 2])
 y2:tensor([[[[[[0., 0.]],

           [[0., 0.]]]],



         [[[[0., 0.]],

           [[0., 0.]]]]],




        [[[[[0., 0.]],

           [[0., 0.]]]],



         [[[[0., 0.]],

           [[0., 0.]]]]]])
 torch.Size([2, 2, 1, 2, 1, 2])
 y3:tensor([[[[[[0., 0.]],

           [[0., 0.]]]],



         [[[[0., 0.]],

           [[0., 0.]]]]],




        [[[[[0., 0.]],

           [[0., 0.]]]],



         [[[[0., 0.]],

           [[0., 0.]]]]]])
 torch.Size([2, 2, 1, 2, 1, 2])
 y4:tensor([[[[[0., 0.]],

          [[0., 0.]]],


         [[[0.

We see that squeeze method remove the layer with one dimension, and the argument `int dim ` can choose the layer we want to execute squeezing.

In [73]:
# unsqueezed method simply add a dimension in certain index
y1_unsqueezed = y1.unsqueeze(dim=1)
y1_unsqueezed2 = y1.unsqueeze(dim=2)
y1,y1.size(),y1_unsqueezed,y1_unsqueezed.size(),y1_unsqueezed2,y1_unsqueezed2.size()

(tensor([[[[0., 0.],
           [0., 0.]],
 
          [[0., 0.],
           [0., 0.]]],
 
 
         [[[0., 0.],
           [0., 0.]],
 
          [[0., 0.],
           [0., 0.]]]]),
 torch.Size([2, 2, 2, 2]),
 tensor([[[[[0., 0.],
            [0., 0.]],
 
           [[0., 0.],
            [0., 0.]]]],
 
 
 
         [[[[0., 0.],
            [0., 0.]],
 
           [[0., 0.],
            [0., 0.]]]]]),
 torch.Size([2, 1, 2, 2, 2]),
 tensor([[[[[0., 0.],
            [0., 0.]]],
 
 
          [[[0., 0.],
            [0., 0.]]]],
 
 
 
         [[[[0., 0.],
            [0., 0.]]],
 
 
          [[[0., 0.],
            [0., 0.]]]]]),
 torch.Size([2, 2, 1, 2, 2]))

#### torch.permute
Rearrange the dimension of target tensor into a certain order.

In [76]:
#permute(input/tensor,dims/tuple_oof_order)
x = torch.rand(200,210,3) # like height,width,color
x_permuted = x.permute(2,0,1) #just a new order of dim of each layers
x.size(),x_permuted.size()
#Attention x_permuted share the same storage with x(like reshape and view)

(torch.Size([200, 210, 3]), torch.Size([3, 200, 210]))