<a href="https://colab.research.google.com/github/YKXu-c/MachineLearning_pytorch_RL_DLExamples/blob/main/00_basical_pytorch_using.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Basic opearation of pytorch
Resource: My note https://rust.oakk.space/article/29224ed4-ef88-80f1-9413-f86ee4e3344a and mrdbourke's great cource https://github.com/mrdbourke/pytorch-deep-learning

In [1]:

print("Just a test!")


Just a test!


In [2]:

!nvidia-smi


Tue Nov 18 00:30:14 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   39C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
import torch
print(torch.__version__)

2.8.0+cu126


In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import time
# These are used for data reading, tensor/matrix, data plotting

## Tensors
### Creating tensors

In [5]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
scalar.item()

7

In [8]:
# Vector
vector = torch.tensor([6,7])
vector



tensor([6, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
#Matrix
Matrix = torch.tensor([[11,12],
            [21,22]])
Matrix

tensor([[11, 12],
        [21, 22]])

In [12]:
Matrix.ndim

2

In [13]:
Matrix[0]


tensor([11, 12])

In [14]:
Matrix.shape

torch.Size([2, 2])

In [15]:
#TENSOR of order 3
TENSOR1 = torch.tensor([[[11,12,13],
            [21,22,23],
            [31,32,33]]])
TENSOR1

tensor([[[11, 12, 13],
         [21, 22, 23],
         [31, 32, 33]]])

In [16]:
TENSOR1.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR2 = torch.tensor([[[11,12,13],
            [21,22,23]]])
TENSOR2.shape

torch.Size([1, 2, 3])

In [18]:
len(TENSOR2) # method len() just gives the highest order of a tensor

1

In [19]:
# TENSOR3 = torch.tensor([[[11,13],
#             [21,22,23]]])
# TENSOR3.shape

The dimension of "sub" tensor should be the same. You can run this block and see the Error given by compiler.

### Random tensors
Why random tensors?
We can indentify any tensor by give exact elements.
In a neural net works learn, start from a random tensor is a btter choice.
Then we can adjust elements in this tensor to represent data properly.
`Start with random numbers -> look at data -> update randm numbers -> look at data -> update -> ......
Check Torch.RAND

In [20]:
# Create a random tensor of size (3,4) which is a matrix (have 3 vectors and each vector has 4 scalar)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2469, 0.4081, 0.3180, 0.3352],
        [0.3084, 0.1807, 0.0371, 0.0091],
        [0.6882, 0.0551, 0.9855, 0.0948]])

In [21]:
# Create a random tensor with similar shape to an image tensor
# a image tensor should have 3 dimensions: hight, width, color
random_image_size_tensor = torch.rand(size=(3,224,224))# color, hight, width
random_image_size_tensor

tensor([[[0.9085, 0.3143, 0.1347,  ..., 0.7464, 0.3157, 0.7939],
         [0.8132, 0.4633, 0.9257,  ..., 0.6163, 0.8670, 0.2303],
         [0.6062, 0.1003, 0.1001,  ..., 0.7427, 0.5426, 0.3807],
         ...,
         [0.7938, 0.4887, 0.5128,  ..., 0.9767, 0.5528, 0.2736],
         [0.8367, 0.6482, 0.4693,  ..., 0.1045, 0.6600, 0.8971],
         [0.5060, 0.1181, 0.6569,  ..., 0.3393, 0.0257, 0.6060]],

        [[0.8354, 0.2863, 0.5764,  ..., 0.1713, 0.0072, 0.5332],
         [0.5841, 0.8844, 0.2905,  ..., 0.5881, 0.2058, 0.2932],
         [0.0054, 0.6217, 0.3248,  ..., 0.1440, 0.3809, 0.8288],
         ...,
         [0.2322, 0.0639, 0.9279,  ..., 0.8868, 0.7578, 0.4918],
         [0.4651, 0.8216, 0.3684,  ..., 0.9617, 0.1639, 0.2863],
         [0.0637, 0.6231, 0.4060,  ..., 0.7715, 0.6510, 0.0361]],

        [[0.7052, 0.6261, 0.9606,  ..., 0.1710, 0.2298, 0.0240],
         [0.7203, 0.2643, 0.3455,  ..., 0.5641, 0.1433, 0.6080],
         [0.6416, 0.9365, 0.0871,  ..., 0.2839, 0.9698, 0.

In this way, we can represent any images into a tensor in pytorch saved in our memory of computer.

### Create a tensor with only Zeros or ones

In [22]:
# create a tensor with all zeros
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
# create a tensor with all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

A tensor has a property called (dataType)


In [24]:
ones.dtype

torch.float32

### Create a range of tensors and tensors-like

In [25]:
torch.range(0,10)

/tmp/ipython-input-497691777.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [26]:
one_to_ten = torch.arange(1,11)#torch.arange(start = 1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
one_to_101 = torch.arange(start = 1, end=101, step=6)
one_to_101

tensor([ 1,  7, 13, 19, 25, 31, 37, 43, 49, 55, 61, 67, 73, 79, 85, 91, 97])

If we want to create a tensor with just the same shape of a tensor we already generated, we can do as below:

In [28]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
many_zeros = torch.zeros_like(input=random_image_size_tensor)
many_zeros

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])

### Tensor datatypes (attributes)
**Note:** There are 3 normal errors when we run into with Pytorch
1. wrong datatype, `tensor.dtype`
2. wrong shape, `tensor.shape` or `tensor.size()`
3. not on right device, `tensor.device`

In [30]:
# Float 32 tensor(defalut if we type a decimal number)
float_32_tensor = torch.tensor([3.0,6,9],dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [31]:
float_32_tensor.dtype

torch.float32

In [32]:
int_64_tensor = torch.tensor([3,6,9],dtype=None)
int_64_tensor

tensor([3, 6, 9])

In [33]:
int_64_tensor.dtype

torch.int64

In [34]:
# change to certain datatype
float_16_tensor = torch.tensor([3,6,9],dtype=torch.float16)
print(float_16_tensor,"'s datatype is ",float_16_tensor.dtype)

tensor([3., 6., 9.], dtype=torch.float16) 's datatype is  torch.float16


In [35]:
# basic parameters
a_torch_tensor = torch.tensor([3.0,6.0,9.0],
                dtype=None,   # different precision of numbers in a torch.tensor, there are also complex number, torch.complex32
                device=None,   # cpu,cuda,etc.
                requires_grad=False) # whether or not to track the gradient of tensor

In [36]:
another_torch_tensor = torch.tensor([3.0,6.0,9.0],
                dtype=torch.complex64,   # different precision of numbers in a torch.tensor, there are also complex number, torch.complex32
                device='cuda',   # cpu,cuda,etc.
                requires_grad=True) # whether or not to track the gradient of tensor
print(f"{another_torch_tensor}'s datatype is {another_torch_tensor.dtype}")

tensor([3.+0.j, 6.+0.j, 9.+0.j], device='cuda:0', requires_grad=True)'s datatype is torch.complex64


### Manipulating Tensors （tensor operations）
* Addition
* Subtraction
* Multiplication
* Division
* Matrix multiplication


In [37]:
# Create a tensor and add 10 to it
temp_tensor = torch.rand(2,3,4)
temp_tensor_prime = temp_tensor+10
print(f"initial random tensor is {temp_tensor}, after operation being{temp_tensor_prime}")

initial random tensor is tensor([[[0.4400, 0.2649, 0.7003, 0.5370],
         [0.9383, 0.7160, 0.0474, 0.1065],
         [0.1833, 0.6062, 0.2221, 0.4716]],

        [[0.6050, 0.8221, 0.8063, 0.7513],
         [0.8200, 0.3744, 0.0028, 0.5695],
         [0.5298, 0.4370, 0.8759, 0.8795]]]), after operation beingtensor([[[10.4400, 10.2649, 10.7003, 10.5370],
         [10.9383, 10.7160, 10.0474, 10.1065],
         [10.1833, 10.6062, 10.2221, 10.4716]],

        [[10.6050, 10.8221, 10.8063, 10.7513],
         [10.8200, 10.3744, 10.0028, 10.5695],
         [10.5298, 10.4370, 10.8759, 10.8795]]])


In [38]:
# Substract is similiar
temp_tensor = torch.rand(2,3,4)
temp_tensor_pp = torch.rand_like(input=temp_tensor)
temp_tensor_prime = temp_tensor-temp_tensor_pp
print(f"initial random tensors is {temp_tensor}\n and {temp_tensor_pp},\n after operation being{temp_tensor_prime}")

initial random tensors is tensor([[[0.8265, 0.7527, 0.5744, 0.4229],
         [0.5239, 0.7008, 0.4635, 0.3951],
         [0.6495, 0.1653, 0.3824, 0.3716]],

        [[0.6044, 0.2228, 0.8319, 0.4765],
         [0.4955, 0.9613, 0.1473, 0.8579],
         [0.8087, 0.6876, 0.6844, 0.6421]]])
 and tensor([[[0.7545, 0.8215, 0.7297, 0.6933],
         [0.4816, 0.2821, 0.9592, 0.3898],
         [0.2853, 0.7222, 0.4121, 0.5284]],

        [[0.4223, 0.6065, 0.6363, 0.1686],
         [0.0066, 0.0342, 0.6217, 0.5043],
         [0.0881, 0.6621, 0.4874, 0.8855]]]),
 after operation beingtensor([[[ 0.0720, -0.0688, -0.1553, -0.2705],
         [ 0.0423,  0.4187, -0.4957,  0.0053],
         [ 0.3641, -0.5570, -0.0297, -0.1568]],

        [[ 0.1821, -0.3837,  0.1956,  0.3078],
         [ 0.4889,  0.9271, -0.4744,  0.3536],
         [ 0.7205,  0.0255,  0.1970, -0.2433]]])


Then we takle a look at multiplication and matrix multiplication of tensors

In [39]:
temp_tensor = float_16_tensor * float_32_tensor
print(temp_tensor,temp_tensor.dtype)

tensor([ 9., 36., 81.]) torch.float32


In [40]:
temp_tensor = int_64_tensor * float_32_tensor
print(temp_tensor,temp_tensor.dtype)

tensor([ 9., 36., 81.]) torch.float32


This is just multiplicating elements with same index and put them into a new tensor.

We can use matrix multiplication (dot product,just like in `Matlab`) to achieve tensor contraction.


In [41]:
temp_tensor = torch.matmul(float_16_tensor, float_16_tensor)
print(f"initial tensor is {float_16_tensor}, result is {temp_tensor}")

initial tensor is tensor([3., 6., 9.], dtype=torch.float16), result is 126.0


In [42]:
%%time
float_16_tensor_prime = torch.tensor([[1,2,3],[1,2,3]])
temp_tensor = torch.matmul(float_16_tensor_prime, torch.transpose(float_16_tensor_prime,0,1))
# Here we use the method transpose to transpose tensor(2*3) to (3*2)
# Attention! the arguments 0,1 is to label which two index of tensor we want to trans
print(f"initial tensor is {float_16_tensor_prime}with size {float_16_tensor_prime.size()}, result is {temp_tensor}")
# From the result and recall the rule of matrix multiplication, we can see matrix in torch.tensor is saved by row

initial tensor is tensor([[1, 2, 3],
        [1, 2, 3]])with size torch.Size([2, 3]), result is tensor([[14, 14],
        [14, 14]])
CPU times: user 1.6 ms, sys: 115 µs, total: 1.71 ms
Wall time: 9.68 ms


In [43]:
# If you are familiar with contraction of tensor and Einstain sum rule, we can do this:
%%time
random_tensor = torch.rand(2,3,4)
random_tensor_trans13 = torch.transpose(random_tensor,0,2)
temp_tensor = torch.einsum('ijk,kji->',[random_tensor,random_tensor_trans13])
print(f"initial tensor is {random_tensor}\n result is {temp_tensor}")

initial tensor is tensor([[[0.8102, 0.3417, 0.5508, 0.9796],
         [0.1901, 0.3090, 0.2884, 0.9276],
         [0.1287, 0.5435, 0.3426, 0.3279]],

        [[0.9087, 0.3831, 0.8569, 0.6858],
         [0.4078, 0.5856, 0.7945, 0.5518],
         [0.9985, 0.3712, 0.6956, 0.9483]]])
 result is 9.788243293762207
CPU times: user 10.1 ms, sys: 2.01 ms, total: 12.1 ms
Wall time: 14.1 ms


In [44]:
# A test of superlarge tensor contraction
# If the video memory is enough, this is super effective in cuda
%%time
random_tensor = torch.rand(size=(1000,300,4000),device='cuda')
random_tensor_trans13 = torch.transpose(random_tensor,0,2)
temp_tensor = torch.einsum('ijk,kji->',[random_tensor,random_tensor_trans13])
print(f"initial tensor is {random_tensor}\n result is {temp_tensor}")

initial tensor is tensor([[[0.6637, 0.6788, 0.4455,  ..., 0.6638, 0.4259, 0.7884],
         [0.2817, 0.5655, 0.0068,  ..., 0.0576, 0.6691, 0.3153],
         [0.4108, 0.6662, 0.5002,  ..., 0.3957, 0.0114, 0.1490],
         ...,
         [0.3297, 0.3148, 0.6269,  ..., 0.2133, 0.6512, 0.7422],
         [0.3739, 0.9472, 0.2596,  ..., 0.7893, 0.2409, 0.8973],
         [0.5355, 0.5123, 0.6156,  ..., 0.1909, 0.5438, 0.9596]],

        [[0.1558, 0.5775, 0.3531,  ..., 0.3796, 0.8807, 0.8417],
         [0.5293, 0.4366, 0.1956,  ..., 0.3119, 0.1352, 0.0963],
         [0.0097, 0.8760, 0.4067,  ..., 0.4856, 0.2119, 0.9657],
         ...,
         [0.4261, 0.5012, 0.7319,  ..., 0.2460, 0.6009, 0.4207],
         [0.0439, 0.4390, 0.5434,  ..., 0.9894, 0.2688, 0.1028],
         [0.1643, 0.4998, 0.0450,  ..., 0.8433, 0.7312, 0.0679]],

        [[0.3918, 0.0647, 0.6159,  ..., 0.9713, 0.9867, 0.1609],
         [0.0112, 0.4289, 0.7802,  ..., 0.4060, 0.6343, 0.2396],
         [0.4851, 0.5314, 0.9514,  ..., 

### Finding the min,max,mean,sum,etc of a tensor(tensor aggregation，统计)

In [45]:
temp_tensor = torch.rand(2,3,4)
max = torch.mean(temp_tensor)
print(f"The tensor is {temp_tensor},\n \
the min is{torch.min(temp_tensor)}\n \
the max is {torch.max(temp_tensor)}\n \
the mean is {torch.mean(temp_tensor)}")
print(f"the dtype of it is: {max.dtype}")
# Attention! torch.mean requires the dtype of element of tensor being float or complex
# Or this way to use methods:
print(temp_tensor.mean())
print(f"the dtype of it is: {temp_tensor.mean().dtype}")
print(temp_tensor.type(torch.complex128).mean())
# They have the same dtype but different display, that is caused by print/printf
print(f"{temp_tensor.mean()}")
# printf call the __repr__ method of tensor, but print call __str__

The tensor is tensor([[[0.8698, 0.1193, 0.1645, 0.0237],
         [0.1048, 0.6803, 0.0585, 0.5533],
         [0.9700, 0.3458, 0.3509, 0.1035]],

        [[0.6031, 0.6084, 0.3642, 0.8795],
         [0.2586, 0.8336, 0.7126, 0.6605],
         [0.8346, 0.7644, 0.6783, 0.9033]]]),
 the min is0.023669898509979248
 the max is 0.9699611067771912
 the mean is 0.5185593366622925
the dtype of it is: torch.float32
tensor(0.5186)
the dtype of it is: torch.float32
tensor(0.5186+0.j, dtype=torch.complex128)
0.5185593366622925


### Finding positional min and max
* That means we find the argument(index) of the min in torch.**tensor**

In [46]:
# argmin is used to find the argument of min in a list or an array.
#
print(f"tensor is {temp_tensor}\n \
position of min is {temp_tensor.argmin()}\n \
position of min is {torch.unravel_index(temp_tensor.argmin(),temp_tensor.shape)}")
# unravel_index helps us translate 1-dim index to coordinate of .shape

tensor is tensor([[[0.8698, 0.1193, 0.1645, 0.0237],
         [0.1048, 0.6803, 0.0585, 0.5533],
         [0.9700, 0.3458, 0.3509, 0.1035]],

        [[0.6031, 0.6084, 0.3642, 0.8795],
         [0.2586, 0.8336, 0.7126, 0.6605],
         [0.8346, 0.7644, 0.6783, 0.9033]]])
 position of min is 3
 position of min is (tensor(0), tensor(0), tensor(3))


### Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor(like the same tensor but different perspective, always same memory!)
* Stacking - combines seceral tensors in certain way: h-stack, v-stack, side-by-side, etc.
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add `1` dimension into a target tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way(We can say that *斜体文本*`Permute` changes the dimension of layer in a tensor)


In [47]:
# use x for easy typing code
x = torch.rand(2,3,4)
print(f"{x}")

tensor([[[0.1440, 0.3805, 0.9511, 0.7071],
         [0.5833, 0.5600, 0.4446, 0.3937],
         [0.8758, 0.1553, 0.5703, 0.4859]],

        [[0.9004, 0.5026, 0.7158, 0.0935],
         [0.2299, 0.5181, 0.3002, 0.8664],
         [0.6645, 0.2418, 0.0335, 0.8900]]])


In [48]:
# Using of reshape:must has the same number of elements
x_reshaped = x.reshape(2,2,3,2)
print(f"original:{x} \n \
after reshaping: {x_reshaped},\n \
shape is {x_reshaped.shape}")

original:tensor([[[0.1440, 0.3805, 0.9511, 0.7071],
         [0.5833, 0.5600, 0.4446, 0.3937],
         [0.8758, 0.1553, 0.5703, 0.4859]],

        [[0.9004, 0.5026, 0.7158, 0.0935],
         [0.2299, 0.5181, 0.3002, 0.8664],
         [0.6645, 0.2418, 0.0335, 0.8900]]]) 
 after reshaping: tensor([[[[0.1440, 0.3805],
          [0.9511, 0.7071],
          [0.5833, 0.5600]],

         [[0.4446, 0.3937],
          [0.8758, 0.1553],
          [0.5703, 0.4859]]],


        [[[0.9004, 0.5026],
          [0.7158, 0.0935],
          [0.2299, 0.5181]],

         [[0.3002, 0.8664],
          [0.6645, 0.2418],
          [0.0335, 0.8900]]]]),
 shape is torch.Size([2, 2, 3, 2])


We see that reshape does not change the element order of tensor, just change them into a new tensor with the same total size.

#### Change the view of tensor

In [49]:
# Change the view of tensor
z = x.view(2,2,3,2)
z, z.shape

(tensor([[[[0.1440, 0.3805],
           [0.9511, 0.7071],
           [0.5833, 0.5600]],
 
          [[0.4446, 0.3937],
           [0.8758, 0.1553],
           [0.5703, 0.4859]]],
 
 
         [[[0.9004, 0.5026],
           [0.7158, 0.0935],
           [0.2299, 0.5181]],
 
          [[0.3002, 0.8664],
           [0.6645, 0.2418],
           [0.0335, 0.8900]]]]),
 torch.Size([2, 2, 3, 2]))

It seems like there is no different with reshape!

If we check the memory, we will find they share the same memory storage.

Well, the difference between reshape and view is that `view` requeires a continuing storage space.

In [50]:
id(x),id(z),id(x_reshaped)

(139645579773584, 139645576855792, 139645579065968)

In [51]:
x.storage().data_ptr, z.storage().data_ptr, x_reshaped.storage().data_ptr

/tmp/ipython-input-3045457666.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  x.storage().data_ptr, z.storage().data_ptr, x_reshaped.storage().data_ptr


(<bound method TypedStorage.data_ptr of  0.14401698112487793
  0.3805376887321472
  0.9510894417762756
  0.7070860266685486
  0.5833374261856079
  0.5600249767303467
  0.4446026086807251
  0.39368271827697754
  0.8757757544517517
  0.15533477067947388
  0.57029789686203
  0.4859399199485779
  0.9003600478172302
  0.5025776624679565
  0.7158144116401672
  0.09351217746734619
  0.2298729419708252
  0.5181494951248169
  0.30024832487106323
  0.8664433360099792
  0.6645290851593018
  0.2417508363723755
  0.03347957134246826
  0.8899645805358887
 [torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 24]>,
 <bound method TypedStorage.data_ptr of  0.14401698112487793
  0.3805376887321472
  0.9510894417762756
  0.7070860266685486
  0.5833374261856079
  0.5600249767303467
  0.4446026086807251
  0.39368271827697754
  0.8757757544517517
  0.15533477067947388
  0.57029789686203
  0.4859399199485779
  0.9003600478172302
  0.5025776624679565
  0.7158144116401672
  0.09351217746734619



#### Stack tensor from top to each orther.

 Let us just take a simply example


In [52]:
# Stack tensor from top to each orther. Let us just take a simply example
x = torch.rand(2,3)
x_stacked_dim0 = torch.stack([x,x,x],dim=0)
x_stacked_dim1 = torch.stack([x,x,x],dim=1)
x_stacked_dim2 = torch.stack([x,x,x],dim=2)
x_stacked_dim_minus_2 = torch.stack([x,x,x],dim=-2)
x,x_stacked_dim0,x_stacked_dim1,x_stacked_dim2,x_stacked_dim_minus_2

(tensor([[0.7487, 0.5414, 0.8290],
         [0.1485, 0.5940, 0.9889]]),
 tensor([[[0.7487, 0.5414, 0.8290],
          [0.1485, 0.5940, 0.9889]],
 
         [[0.7487, 0.5414, 0.8290],
          [0.1485, 0.5940, 0.9889]],
 
         [[0.7487, 0.5414, 0.8290],
          [0.1485, 0.5940, 0.9889]]]),
 tensor([[[0.7487, 0.5414, 0.8290],
          [0.7487, 0.5414, 0.8290],
          [0.7487, 0.5414, 0.8290]],
 
         [[0.1485, 0.5940, 0.9889],
          [0.1485, 0.5940, 0.9889],
          [0.1485, 0.5940, 0.9889]]]),
 tensor([[[0.7487, 0.7487, 0.7487],
          [0.5414, 0.5414, 0.5414],
          [0.8290, 0.8290, 0.8290]],
 
         [[0.1485, 0.1485, 0.1485],
          [0.5940, 0.5940, 0.5940],
          [0.9889, 0.9889, 0.9889]]]),
 tensor([[[0.7487, 0.5414, 0.8290],
          [0.7487, 0.5414, 0.8290],
          [0.7487, 0.5414, 0.8290]],
 
         [[0.1485, 0.5940, 0.9889],
          [0.1485, 0.5940, 0.9889],
          [0.1485, 0.5940, 0.9889]]]))

`dim`: The dimension along which to stack the tensors.

In above examples:
x has shape `2*3`

`dim=0`: `2*3` -> `3*2*3`, the new dimension inserts in front of any layers

`dim=1`: `2*3` -> `2*3*3`, the new dimension inserts between index [0] and index [1]

`dim=2`: `2*3` -> `2*3*3`, the new dimension inserts between index [1] and index [2]

`dim=-2`: the lowerst layer has 3 elements, so `-2` is the same as `1`, just like the index of list in `python`.

#### torch.squeeze()
- removing 1-dimension from a target tensor


In [53]:
# use zeros to look at squeeze method
x = torch.zeros(2,2,1,2,1,2)
y1 = torch.squeeze(x)
y2 = torch.squeeze(x,0)
y3 = torch.squeeze(x,1)
y4 = torch.squeeze(x,dim=2)
y5 = torch.squeeze(x,dim=(2,4))
print(f"x:{x}\n {x.size()}\n \
y1:{y1}\n {y1.size()}\n \
y2:{y2}\n {y2.size()}\n \
y3:{y3}\n {y3.size()}\n \
y4:{y4}\n {y4.size()}\n \
y5:{y5}\n {y5.size()}\n")

x:tensor([[[[[[0., 0.]],

           [[0., 0.]]]],



         [[[[0., 0.]],

           [[0., 0.]]]]],




        [[[[[0., 0.]],

           [[0., 0.]]]],



         [[[[0., 0.]],

           [[0., 0.]]]]]])
 torch.Size([2, 2, 1, 2, 1, 2])
 y1:tensor([[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]])
 torch.Size([2, 2, 2, 2])
 y2:tensor([[[[[[0., 0.]],

           [[0., 0.]]]],



         [[[[0., 0.]],

           [[0., 0.]]]]],




        [[[[[0., 0.]],

           [[0., 0.]]]],



         [[[[0., 0.]],

           [[0., 0.]]]]]])
 torch.Size([2, 2, 1, 2, 1, 2])
 y3:tensor([[[[[[0., 0.]],

           [[0., 0.]]]],



         [[[[0., 0.]],

           [[0., 0.]]]]],




        [[[[[0., 0.]],

           [[0., 0.]]]],



         [[[[0., 0.]],

           [[0., 0.]]]]]])
 torch.Size([2, 2, 1, 2, 1, 2])
 y4:tensor([[[[[0., 0.]],

          [[0., 0.]]],


         [[[0.

We see that squeeze method remove the layer with one dimension, and the argument `int dim ` can choose the layer we want to execute squeezing.

In [54]:
# unsqueezed method simply add a dimension in certain index
y1_unsqueezed = y1.unsqueeze(dim=1)
y1_unsqueezed2 = y1.unsqueeze(dim=2)
y1,y1.size(),y1_unsqueezed,y1_unsqueezed.size(),y1_unsqueezed2,y1_unsqueezed2.size()

(tensor([[[[0., 0.],
           [0., 0.]],
 
          [[0., 0.],
           [0., 0.]]],
 
 
         [[[0., 0.],
           [0., 0.]],
 
          [[0., 0.],
           [0., 0.]]]]),
 torch.Size([2, 2, 2, 2]),
 tensor([[[[[0., 0.],
            [0., 0.]],
 
           [[0., 0.],
            [0., 0.]]]],
 
 
 
         [[[[0., 0.],
            [0., 0.]],
 
           [[0., 0.],
            [0., 0.]]]]]),
 torch.Size([2, 1, 2, 2, 2]),
 tensor([[[[[0., 0.],
            [0., 0.]]],
 
 
          [[[0., 0.],
            [0., 0.]]]],
 
 
 
         [[[[0., 0.],
            [0., 0.]]],
 
 
          [[[0., 0.],
            [0., 0.]]]]]),
 torch.Size([2, 2, 1, 2, 2]))

#### torch.permute
Rearrange the dimension of target tensor into a certain order.

In [55]:
#permute(input/tensor,dims/tuple_oof_order)
x = torch.rand(200,210,3) # like height,width,color
x_permuted = x.permute(2,0,1) #just a new order of dim of each layers
x.size(),x_permuted.size()
#Attention x_permuted share the same storage with x(like reshape and view)

(torch.Size([200, 210, 3]), torch.Size([3, 200, 210]))

### selecting or reading data from tensors

Indexing just like numpy/array

In [56]:
x = torch.rand(2,3,4)
x,time.time(),x[0][2][3],time.time(),x[0,2,3],time.time(),x[1,:,:]
#[1,2,3] is a better way,
#It is faster, no intermediate variable and has advanced usage.

(tensor([[[0.6230, 0.4403, 0.6688, 0.8201],
          [0.9002, 0.9927, 0.8574, 0.0400],
          [0.1354, 0.0243, 0.9551, 0.9609]],
 
         [[0.1569, 0.4650, 0.4613, 0.0491],
          [0.3016, 0.9515, 0.2277, 0.3731],
          [0.9980, 0.3463, 0.5316, 0.3162]]]),
 1763425829.6951742,
 tensor(0.9609),
 1763425829.6952937,
 tensor(0.9609),
 1763425829.6953142,
 tensor([[0.1569, 0.4650, 0.4613, 0.0491],
         [0.3016, 0.9515, 0.2277, 0.3731],
         [0.9980, 0.3463, 0.5316, 0.3162]]))

### Pytorch tensors & Numpy

Pytorch has functionality to interact with Numpy.(ndarray used to save matrix)

* Data in Numpy -> Pytorch Tensor : `torch.from_numpy(ndarray)`

* Tensor -> Numpy : `torch.Tensor.numpy()`


In [57]:
# array to tensor
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
tensor_change_type = torch.from_numpy(array).type(torch.float32)
array,tensor,tensor_change_type.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 torch.float32)

Be careful! The default datatype of array is different with tensor.

And `Numpy->Tensor` reflects the dtype of numpy `float64`.

In [58]:
# Changing the value of array influence tensor or not?
tensor_another = torch.tensor(array)
array += 1
array,tensor,tensor_another

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

The behavior is different with the version in Youtube vedio!
`torch.tensor` and `torch.from_numpy` are different.

In [59]:
# Tensor to numoy, The default dtype of tensor is copied into numpy array
tensorEx = torch.ones(7)
numpy_from_tensor = tensorEx.numpy()
tensorEx,numpy_from_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [60]:
# Changing is also translable
tensorEx += 1
tensorEx,numpy_from_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([2., 2., 2., 2., 2., 2., 2.], dtype=float32))

## Reproducibility （trying to take random out of random）\[ get the same or similiar result in every time of running the code, 重现性 \]

In short, how a neural network learns:
`start with random numbers -> tensor operation -> update those datas -> update again and again`

The result should be convergent to some confirmed tensor, so we call this method having reproducibility.

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.


Essentially, what the **random seed** does is "flavour" the randomness.(We do not talk about the problem of random in computer science here.)

We will see it in action.

In [61]:
# Create two random tensors
random_tensor_A = torch.rand(2,3,4)
random_tensor_B = torch.rand(2,3,4)
print(f"{random_tensor_A}\n {random_tensor_B}\n {random_tensor_A == random_tensor_B}")

tensor([[[0.8709, 0.7054, 0.4830, 0.4888],
         [0.8425, 0.5238, 0.7174, 0.7136],
         [0.3696, 0.3604, 0.5884, 0.6848]],

        [[0.6538, 0.6699, 0.4655, 0.3016],
         [0.3137, 0.2341, 0.0027, 0.4628],
         [0.1975, 0.3780, 0.0267, 0.3759]]])
 tensor([[[0.1395, 0.1553, 0.8618, 0.9593],
         [0.5792, 0.1090, 0.2353, 0.5905],
         [0.4558, 0.0800, 0.0192, 0.5249]],

        [[0.0034, 0.7614, 0.0052, 0.0574],
         [0.5050, 0.5247, 0.8740, 0.7922],
         [0.8574, 0.0930, 0.3667, 0.6234]]])
 tensor([[[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]],

        [[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]])


In [62]:
# Create random tensors with certain random seed
# Notice! The usage of manual_seed should be added in each time of calling torch.rand
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(2,3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(2,3,4)
print(f"{random_tensor_A}\n {random_tensor_B}\n {random_tensor_A == random_tensor_B}")

tensor([[[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]],

        [[0.8694, 0.5677, 0.7411, 0.4294],
         [0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317]]])
 tensor([[[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]],

        [[0.8694, 0.5677, 0.7411, 0.4294],
         [0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317]]])
 tensor([[[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]],

        [[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]])


By this way, we can use our own method to generate random seed and use the seed to create tensors.

## Running tensors and PyTorch objects on GPUs and making faster computations.

- CUDA + NVIDIA hardware + PyTorch(Nowdays, GPU,TPU,NPU have so great development, I may talk about them in another blog.)
- Check for GPU access with Pytorch /url[https://docs.pytorch.org/docs/stable/notes/cuda.html]

- Put tensor on GPU back to CPU

In [63]:
# Check
torch.cuda.is_available()

True

In [64]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [65]:
torch.cuda.device_count()

1

As numpy can not deal with data on GPU, we always need to take tensor back on CPU for visualization of data or transport data to orther code.

In [71]:
tensor_on_gpu = torch.randn(2,3,4, device='cuda')
tensor_back_to_cpu = tensor_on_gpu.detach().cpu().numpy()
print(f"Tensor on GPU device: {tensor_on_gpu},{tensor_on_gpu.device}\n \
Tensor back to cpu: {tensor_back_to_cpu},{tensor_back_to_cpu.device}\n \
{type(tensor_back_to_cpu)}")

Tensor on GPU device: tensor([[[-0.6974, -1.8688, -0.8832, -1.6627],
         [-0.4324,  0.9505,  0.6620,  0.0446],
         [ 0.5720,  2.1951, -0.2474, -1.3831]],

        [[ 0.0602, -0.2431,  1.3181,  0.5211],
         [-0.6087,  0.1000, -0.8960, -0.9373],
         [-0.2666,  1.5304,  0.5584, -0.9451]]], device='cuda:0'),cuda:0
 Tensor back to cpu: [[[-0.6973659  -1.8688258  -0.8831874  -1.6627042 ]
  [-0.43243223  0.9504958   0.6620458   0.04456767]
  [ 0.57203025  2.1950514  -0.24739435 -1.3831176 ]]

 [[ 0.06023683 -0.24308123  1.3181238   0.5210878 ]
  [-0.6087268   0.09999156 -0.89596015 -0.9372563 ]
  [-0.26658922  1.5304362   0.5583864  -0.94508106]]],cpu
 <class 'numpy.ndarray'>


### Exercises
https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises