<a href="https://colab.research.google.com/github/YKXu-c/ReinforcementExamples/blob/main/00_basical_pytorch_using.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Basic opearation of pytorch
Resource: My note https://rust.oakk.space/article/29224ed4-ef88-80f1-9413-f86ee4e3344a and mrdbourke's great cource https://github.com/mrdbourke/pytorch-deep-learning

In [227]:

print("Just a test!")


Just a test!


In [228]:

!nvidia-smi


Mon Nov 10 03:02:41 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   74C    P0             34W /   70W |     120MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [229]:
import torch
print(torch.__version__)

2.8.0+cu126


In [230]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# These are used for data reading, tensor/matrix, data plotting

## Tensors
### Creating tensors

In [231]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [232]:
scalar.ndim

0

In [233]:
scalar.item()

7

In [234]:
# Vector
vector = torch.tensor([6,7])
vector



tensor([6, 7])

In [235]:
vector.ndim

1

In [236]:
vector.shape

torch.Size([2])

In [237]:
#Matrix
Matrix = torch.tensor([[11,12],
            [21,22]])
Matrix

tensor([[11, 12],
        [21, 22]])

In [238]:
Matrix.ndim

2

In [239]:
Matrix[0]


tensor([11, 12])

In [240]:
Matrix.shape

torch.Size([2, 2])

In [241]:
#TENSOR of order 3
TENSOR1 = torch.tensor([[[11,12,13],
            [21,22,23],
            [31,32,33]]])
TENSOR1

tensor([[[11, 12, 13],
         [21, 22, 23],
         [31, 32, 33]]])

In [242]:
TENSOR1.shape

torch.Size([1, 3, 3])

In [243]:
TENSOR2 = torch.tensor([[[11,12,13],
            [21,22,23]]])
TENSOR2.shape

torch.Size([1, 2, 3])

In [270]:
len(TENSOR2) # method len() just gives the highest order of a tensor

1

In [244]:
# TENSOR3 = torch.tensor([[[11,13],
#             [21,22,23]]])
# TENSOR3.shape

The dimension of "sub" tensor should be the same. You can run this block and see the Error given by compiler.

### Random tensors
Why random tensors?
We can indentify any tensor by give exact elements.
In a neural net works learn, start from a random tensor is a btter choice.
Then we can adjust elements in this tensor to represent data properly.
`Start with random numbers -> look at data -> update randm numbers -> look at data -> update -> ......
Check Torch.RAND

In [245]:
# Create a random tensor of size (3,4) which is a matrix (have 3 vectors and each vector has 4 scalar)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2834, 0.6012, 0.5485, 0.7363],
        [0.3086, 0.6746, 0.8286, 0.9824],
        [0.8054, 0.6008, 0.2734, 0.0790]])

In [246]:
# Create a random tensor with similar shape to an image tensor
# a image tensor should have 3 dimensions: hight, width, color
random_image_size_tensor = torch.rand(size=(3,224,224))# color, hight, width
random_image_size_tensor

tensor([[[0.6963, 0.4918, 0.7145,  ..., 0.0550, 0.2432, 0.3074],
         [0.3677, 0.0346, 0.0388,  ..., 0.8920, 0.9400, 0.0773],
         [0.2432, 0.7337, 0.6138,  ..., 0.4356, 0.0601, 0.5660],
         ...,
         [0.7670, 0.5351, 0.0735,  ..., 0.0013, 0.9348, 0.1689],
         [0.6780, 0.8967, 0.2528,  ..., 0.4210, 0.4717, 0.0497],
         [0.8038, 0.6153, 0.4877,  ..., 0.7963, 0.8007, 0.6294]],

        [[0.8072, 0.4165, 0.3824,  ..., 0.4960, 0.1677, 0.4199],
         [0.4150, 0.9784, 0.7726,  ..., 0.8803, 0.2771, 0.6520],
         [0.1583, 0.2737, 0.6385,  ..., 0.3106, 0.2508, 0.6259],
         ...,
         [0.3927, 0.0730, 0.2940,  ..., 0.9373, 0.6371, 0.6662],
         [0.5343, 0.9366, 0.0865,  ..., 0.6548, 0.3619, 0.4683],
         [0.5178, 0.8015, 0.5778,  ..., 0.4955, 0.4190, 0.5510]],

        [[0.4601, 0.7146, 0.5698,  ..., 0.6512, 0.8688, 0.6885],
         [0.7527, 0.8422, 0.7616,  ..., 0.7161, 0.7569, 0.3261],
         [0.4199, 0.4894, 0.7766,  ..., 0.8305, 0.4164, 0.

In this way, we can represent any images into a tensor in pytorch saved in our memory of computer.

### Create a tensor with only Zeros or ones

In [247]:
# create a tensor with all zeros
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [248]:
# create a tensor with all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

A tensor has a property called (dataType)


In [249]:
ones.dtype

torch.float32

### Create a range of tensors and tensors-like

In [250]:
torch.range(0,10)

/tmp/ipython-input-497691777.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [251]:
one_to_ten = torch.arange(1,11)#torch.arange(start = 1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [252]:
one_to_101 = torch.arange(start = 1, end=101, step=6)
one_to_101

tensor([ 1,  7, 13, 19, 25, 31, 37, 43, 49, 55, 61, 67, 73, 79, 85, 91, 97])

If we want to create a tensor with just the same shape of a tensor we already generated, we can do as below:

In [253]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [254]:
many_zeros = torch.zeros_like(input=random_image_size_tensor)
many_zeros

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])

### Tensor datatypes (attributes)
**Note:** There are 3 normal errors when we run into with Pytorch
1. wrong datatype, `tensor.dtype`
2. wrong shape, `tensor.shape` or `tensor.size()`
3. not on right device, `tensor.device`

In [255]:
# Float 32 tensor(defalut if we type a decimal number)
float_32_tensor = torch.tensor([3.0,6,9],dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [256]:
float_32_tensor.dtype

torch.float32

In [257]:
int_64_tensor = torch.tensor([3,6,9],dtype=None)
int_64_tensor

tensor([3, 6, 9])

In [258]:
int_64_tensor.dtype

torch.int64

In [259]:
# change to certain datatype
float_16_tensor = torch.tensor([3,6,9],dtype=torch.float16)
print(float_16_tensor,"'s datatype is ",float_16_tensor.dtype)

tensor([3., 6., 9.], dtype=torch.float16) 's datatype is  torch.float16


In [260]:
# basic parameters
a_torch_tensor = torch.tensor([3.0,6.0,9.0],
                dtype=None,   # different precision of numbers in a torch.tensor, there are also complex number, torch.complex32
                device=None,   # cpu,cuda,etc.
                requires_grad=False) # whether or not to track the gradient of tensor

In [261]:
another_torch_tensor = torch.tensor([3.0,6.0,9.0],
                dtype=torch.complex64,   # different precision of numbers in a torch.tensor, there are also complex number, torch.complex32
                device='cuda',   # cpu,cuda,etc.
                requires_grad=True) # whether or not to track the gradient of tensor
print(f"{another_torch_tensor}'s datatype is {another_torch_tensor.dtype}")

tensor([3.+0.j, 6.+0.j, 9.+0.j], device='cuda:0', requires_grad=True)'s datatype is torch.complex64


### Manipulating Tensors （tensor operations）
* Addition
* Subtraction
* Multiplication
* Division
* Matrix multiplication


In [262]:
# Create a tensor and add 10 to it
temp_tensor = torch.rand(2,3,4)
temp_tensor_prime = temp_tensor+10
print(f"initial random tensor is {temp_tensor}, after operation being{temp_tensor_prime}")

initial random tensor is tensor([[[0.0169, 0.1839, 0.9111, 0.1825],
         [0.6492, 0.7073, 0.9249, 0.1882],
         [0.6571, 0.8960, 0.8154, 0.4630]],

        [[0.6185, 0.8086, 0.1103, 0.0618],
         [0.2935, 0.3264, 0.7086, 0.5485],
         [0.7645, 0.4491, 0.2508, 0.6424]]]), after operation beingtensor([[[10.0169, 10.1839, 10.9111, 10.1825],
         [10.6492, 10.7073, 10.9249, 10.1882],
         [10.6571, 10.8960, 10.8154, 10.4630]],

        [[10.6185, 10.8086, 10.1103, 10.0618],
         [10.2935, 10.3264, 10.7086, 10.5485],
         [10.7645, 10.4491, 10.2508, 10.6424]]])


In [263]:
# Substract is similiar
temp_tensor = torch.rand(2,3,4)
temp_tensor_pp = torch.rand_like(input=temp_tensor)
temp_tensor_prime = temp_tensor-temp_tensor_pp
print(f"initial random tensors is {temp_tensor}and {temp_tensor_pp}, after operation being{temp_tensor_prime}")

initial random tensors is tensor([[[0.7736, 0.4236, 0.5893, 0.8746],
         [0.5388, 0.9674, 0.5971, 0.6159],
         [0.7812, 0.1522, 0.5997, 0.8583]],

        [[0.4344, 0.6959, 0.3458, 0.1021],
         [0.4761, 0.0185, 0.3494, 0.7275],
         [0.7204, 0.9937, 0.3826, 0.6100]]])and tensor([[[0.2591, 0.4886, 0.2100, 0.8118],
         [0.4405, 0.4617, 0.9287, 0.2130],
         [0.5973, 0.3126, 0.2236, 0.1719]],

        [[0.2861, 0.9028, 0.7759, 0.2308],
         [0.7923, 0.6545, 0.0444, 0.6184],
         [0.4339, 0.2064, 0.0076, 0.0991]]]), after operation beingtensor([[[ 0.5145, -0.0650,  0.3794,  0.0628],
         [ 0.0983,  0.5058, -0.3317,  0.4029],
         [ 0.1839, -0.1603,  0.3761,  0.6863]],

        [[ 0.1483, -0.2070, -0.4301, -0.1287],
         [-0.3162, -0.6360,  0.3049,  0.1090],
         [ 0.2865,  0.7874,  0.3751,  0.5108]]])


Then we takle a look at multiplication and matrix multiplication of tensors

In [264]:
temp_tensor = float_16_tensor * float_32_tensor
print(temp_tensor,temp_tensor.dtype)

tensor([ 9., 36., 81.]) torch.float32


In [265]:
temp_tensor = int_64_tensor * float_32_tensor
print(temp_tensor,temp_tensor.dtype)

tensor([ 9., 36., 81.]) torch.float32


This is just multiplicating elements with same index and put them into a new tensor.

We can use matrix multiplication (dot product,just like in `Matlab`) to achieve tensor contraction.


In [266]:
temp_tensor = torch.matmul(float_16_tensor, float_16_tensor)
print(f"initial tensor is {float_16_tensor}, result is {temp_tensor}")

initial tensor is tensor([3., 6., 9.], dtype=torch.float16), result is 126.0


In [267]:
float_16_tensor_prime = torch.tensor([[1,2,3],[1,2,3]])
temp_tensor = torch.matmul(float_16_tensor_prime, torch.transpose(float_16_tensor_prime,0,1))
# Here we use the method transpose to transpose tensor(2*3) to (3*2)
# Attention! the arguments 0,1 is to label which two index of tensor we want to trans
print(f"initial tensor is {float_16_tensor_prime}with size {float_16_tensor_prime.size()}, result is {temp_tensor}")
# From the result and recall the rule of matrix multiplication, we can see matrix in torch.tensor is saved by row

initial tensor is tensor([[1, 2, 3],
        [1, 2, 3]])with size torch.Size([2, 3]), result is tensor([[14, 14],
        [14, 14]])


In [268]:
# If you are familiar with contraction of tensor and Einstain sum rule, we can do this:
random_tensor = torch.rand(2,3,4)
random_tensor_trans13 = torch.transpose(random_tensor,0,2)
temp_tensor = torch.einsum('ijk,kji->',[random_tensor,random_tensor_trans13])
print(f"initial tensor is {random_tensor}\n result is {temp_tensor}")

initial tensor is tensor([[[0.2999, 0.9036, 0.0914, 0.4476],
         [0.2604, 0.7809, 0.4841, 0.1641],
         [0.6180, 0.6625, 0.0713, 0.1684]],

        [[0.9197, 0.1497, 0.4745, 0.3615],
         [0.7876, 0.0863, 0.0080, 0.4156],
         [0.8942, 0.3545, 0.5772, 0.5178]]])
 result is 6.459616661071777
